---
name: 'Build and Publish ipinfo'

on:
  schedule:
    - cron: '0 16 * * 3'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Publish ipinfo'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      MAXMIND_KEY: ${{ secrets.MAXMIND_KEY }}
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        run: |
          IPINFO_CVER="$(wget -qO- --tries=5 "https://hub.docker.com/v2/repositories/zzwsec/ipinfo/tags" | grep -o '"name":"[^"]*"' | sed 's/"name":"//;s/"//' | grep -v '^latest$' | sort -Vr | head -n1 || echo "")"
          IPINFO_LVER="$(wget -qO- --tries=5 "https://download.maxmind.com/app/geoip_download?license_key=$MAXMIND_KEY&edition_id=GeoLite2-ASN&suffix=tar.gz.sha256" | awk -F'[ -._]+' '{print $(NF-2)}'"
          NGX_LVER="$(wget -qO- --tries=5 "https://api.github.com/repos/nginx/nginx/releases/latest" | sed -rn 's|^.*tag_name.*release-(.*)",$|\1|p')"
          NGX_ALPINE_LVER="$(docker run --rm nginx:stable-alpine nginx -v 2>&1 | awk -F'[/]' '{print $NF}')"
          GEOIP2_TAG="$(wget -qO- --tries 5 "https://api.github.com/repos/leev/ngx_http_geoip2_module/releases/latest" | jq -r '.tag_name')"
          [[ -z "$IPINFO_LVER" || -z "$NGX_LVER" || -z "$NGX_ALPINE_LVER" || -z "$GEOIP2_TAG" ]] && echo 'Error: Required parameters cannot be empty.' && exit 1
          echo "IPINFO_CVER=$IPINFO_CVER" >> $GITHUB_ENV
          echo "IPINFO_LVER=$IPINFO_LVER" >> $GITHUB_ENV
          echo "NGX_LVER=$NGX_LVER" >> $GITHUB_ENV
          echo "NGX_ALPINE_LVER=$NGX_ALPINE_LVER" >> $GITHUB_ENV
          echo "GEOIP2_TAG=$GEOIP2_TAG" >> $GITHUB_ENV
          [[ ( "$(echo -e "$IPINFO_LVER\n$IPINFO_CVER" | sort -V | head -n1)" != "$IPINFO_LVER" && "$NGX_ALPINE_LVER" == "$NGX_LVER" ) || -z "$IPINFO_CVER" ]] && echo "IS_RENEW=1" >> $GITHUB_ENV

      - name: 'Download GeoLite2 mmdb file'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        run: |
          cd ${{ github.workspace }}/ipinfo
          wget --tries=5 -qO GeoLite2-ASN.tar.gz "https://download.maxmind.com/app/geoip_download?license_key=${MAXMIND_KEY}&edition_id=GeoLite2-ASN&suffix=tar.gz"
          wget --tries=5 -qO GeoLite2-ASN.tar.gz.sha256 "https://download.maxmind.com/app/geoip_download?license_key=${MAXMIND_KEY}&edition_id=GeoLite2-ASN&suffix=tar.gz.sha256"
          sed -i 's/GeoLite2-ASN_[0-9]*.tar.gz/GeoLite2-ASN.tar.gz/g' GeoLite2-ASN.tar.gz.sha256
          sha256sum -c GeoLite2-ASN.tar.gz.sha256
          tar -zxf GeoLite2-ASN.tar.gz --strip 1
          sleep 1
          wget --tries=5 -qO GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?license_key=${MAXMIND_KEY}&edition_id=GeoLite2-Country&suffix=tar.gz"
          wget --tries=5 -qO GeoLite2-Country.tar.gz.sha256 "https://download.maxmind.com/app/geoip_download?license_key=${MAXMIND_KEY}&edition_id=GeoLite2-Country&suffix=tar.gz.sha256"
          sed -i 's/GeoLite2-Country_[0-9]*.tar.gz/GeoLite2-Country.tar.gz/g' GeoLite2-Country.tar.gz.sha256
          sha256sum -c GeoLite2-Country.tar.gz.sha256
          tar -zxf GeoLite2-Country.tar.gz --strip 1

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and Push ipinfo image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.17.0
        with:
          context: ${{ github.workspace }}/ipinfo
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            NGX_LVER=${{ env.NGX_LVER }}
            GEOIP2_TAG=${{ env.GEOIP2_TAG }}
          tags: |
            "${{ env.DOCKER_USERNAME }}/ipinfo:${{ env.IPINFO_LVER }}"
            "${{ env.DOCKER_USERNAME }}/ipinfo:latest"
          push: true

